### ISSUE TITLE
Reduced number of minimum feature size

### ISSUE THREAD

**Issue by BAMcvoelker** [CitrineInformatics/lolo#272]
Hello, 

I noticed that the minimum sample size is limited to at least 8. This can be easily worked around with the np.tile command, repeating the original data until the minimum sample size is reached. I think it would be nice to have this built into the lolopy RF function. 

(I'm fairly new to github and I'm sorry if there is any information missing here or this is not how git hub works. Please feel free to contact me if you need more information).

Example work-around: 

#x= training data
#y=training label

dtr = RandomForestRegressor()
 if y.shape[0]<8:
            x=np.tile(self.x,(8,1))
           y=np.tile(self.y,(8,1))       

        dtr.fit(x,y)

**Comment by bfolie** [comment]
Hi Christoph,

It's true that you can use `np.tile` to create 8 non-unique training data points and get around the minimum sample size. But I don't recommend it. Lolo enforces a minimum of 8 samples because models with very few data points will almost always be unreliable in both their predictions and uncertainty estimates.

I am going to close this issue. Please re-open if I have misunderstood your feature request :)

**Comment by BAMcvoelker** [comment]
Hello BFolie,

sure! Thanks for considering it. I was wondering if there was a mathematical meaning behind the 8? I would come up with 3-4 samples as a lower bound: 2 points to represent a trend, 1 point to omit it in jackknife bootstrapping, and an additional one in case you want to boost the RF. 

Thanks again 🙏

Best regards
